feat(server): Do not hard crash if one product fails to upgrade
The failure during the upgrade of a single product, e pluribus unum,
should not escape the handler in a way that the ENTIRE server fails to
start. Especially considering that following the migrations, the server
re-checks the status of the products anyway...

This fixes an issue observed during the migration to checker auditing
for databases that are VERY big (5-10-15 million reports), that
following a(n otherwise successful) migration, the server still failed
because the database disconnected during the `COMMIT`. (At least from
Python's point-of-view, because the database itself successfully handled
the committing of the transaction.)

-------------------------------------------------------------------------------

This commit is an attempt to fix the following exception:

[INFO][2024-01-21 20:28:14] {migration/report} [c3dad71f8e6b]:216 - Done upgrading 'reports'.
[INFO 2024-01-21 20:28] - Done.
[INFO 2024-01-21 20:28] - Database is up to date.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 561, in do_commit
    dbapi_connection.commit()
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/codechecker/lib/python3/codechecker_common/cli.py", line 209, in main
    sys.exit(args.func(args))
  File "/codechecker/lib/python3/codechecker_server/cmd/server.py", line 425, in __handle
    main(args)
  File "/codechecker/lib/python3/codechecker_server/cmd/server.py", line 1009, in main
    server_init_start(args)
  File "/codechecker/lib/python3/codechecker_server/cmd/server.py", line 936, in server_init_start
    __db_migration(cfg_sql_server, context.run_migration_root,
  File "/codechecker/lib/python3/codechecker_server/cmd/server.py", line 617, in __db_migration
    sess.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 508, in commit
    t[1].commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1762, in commit
    self._do_commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: http://sqlalche.me/e/13/e3q8)